# Use an official Python image based on Alpine Linux
FROM python:3.8-alpine

# Set the working directory
WORKDIR /app

RUN mkdir data

# Copy the current directory contents into the container at /app
COPY python-scripts /app/python-scripts
COPY dependencies/requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the script when the container launches
CMD ["python", "python-scripts/hello-world.py"]